title: pufferfish
email: hello@justus.pw
description: >- # this means to ignore newlines until "baseurl:"
    pufferfish is an awesome configuration file collection for tmux, neovim and
    fish
baseurl: "/pufferfish" # the subpath of your site, e.g. /blog
url: "https://justuswilhelm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: justuswilhelm
github_username:  justuswilhelm

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
